name: Publish

on:
  push:
    tags:
      - 'v*'

jobs:
  create-release:
    runs-on: ubuntu-latest
    outputs:
      release_id: ${{ steps.create-release.outputs.id }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Release
        id: create-release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')

  build:
    needs: create-release

    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Setup environment
        uses: ./.github/actions/setup

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          releaseId: ${{ needs.create-release.outputs.release_id }}